services:

    database:
        image: database
        build: ./database
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust

    api:
        links:
            - database
       
        image: api
        ports:
            - 8001:8001
        build: ./api
        restart: always