services:

    fefuschedule-database:
        image: fefuschedule-database
        build: ./database
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust

    fefuschedule-api:
        links:
            - fefuschedule-database
       
        image: fefuschedule-api
        ports:
            - 8001:8001
        build: ./api
        restart: always