services:

    database:
        image: postgres:16
        ports: 
            - 5432:5432
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust

    api:
        links:
            - database

        env_file:
            - .env

        image: api
        ports:
            - 8001:8001
        build: ./api
        restart: always